export const seedCapsules = [
  {
    title: 'Echange de chaleur et production de chaleur des embryons',
    summary:
      'Comprendre les variations de chaleurs entre les différents incubateurs. Anticiper ces variations. Comment charger différents troupeaux réagissants différemment à la chaleur.',
    creationDate: '2019-09-05T09:10:31.548Z',
    lastUpdate: '2019-09-05T13:01:10.760Z',
    type: 'digital-beedeez',
    status: 'online',
    level: 'intermediary',
    category: '53b27ab61722f10b0000001e',
    categories: ['53b27ab61722f10b0000001e', '540438b80dd1650b00000010'],
    lang: 'fr',
    maxRetry: 9999,
    playMode: 'standard',
    forumDisable: false,
    barcodes: [],
    chapters: [
      {
        mainTitle: "Echange de chaleur dans l'environnement",
        _id: '5d6fc5b2e442c90044234c93',
        name: 'Micro environnement',
        overrideDuration: 4,
        entryQuizz: {
          isPositioningQuiz: true,
          diagnostic: {
            axes: [],
            themes: [],
          },
          lifeNumber: 1,
          questions: [],
          random: false,
          keyName: 'exitQuiz',
        },
        quizz: {
          type: 'question-list',
          diagnostic: {
            axes: [],
            themes: [],
          },
          lifeNumber: 1,
          questions: [
            {
              _id: '5d6fdbecaa9aba005d5690e6',
              explanation:
                'Les œufs incubés procèdent constamment à un échange de chaleur avec le micro-environnement alentour.',
              title:
                'Les oeufs incubés peuvent se réchauffer entre eux dans leur micro environnement ?',
              explanationIsCompulsory: false,
              survey: false,
              choices: [
                {
                  _id: '5d6fdbecaa9aba005d5690e8',
                  value: 0,
                  diagnosticInfos: [],
                  icons: [],
                  good: true,
                },
                {
                  _id: '5d6fdbecaa9aba005d5690e7',
                  value: 1,
                  diagnosticInfos: [],
                  icons: [],
                  good: false,
                },
              ],
              gapFill: {
                gaps: [],
              },
              swipeCards: {
                cards: [],
                choices: [],
              },
              slots: [],
              audios: [],
              icons: [],
              contentType: 'text',
              type: 'truefalse',
            },
            {
              _id: '5d6fdbecaa9aba005d5690e1',
              title:
                'Quels sont les éléments impacté par le facteur de convection ?',
              explanationIsCompulsory: false,
              survey: false,
              choices: [
                {
                  _id: '5d6fdbecaa9aba005d5690e5',
                  value: 0,
                  name: "La vitesse de l'air",
                  diagnosticInfos: [],
                  icons: [],
                  good: false,
                },
                {
                  _id: '5d6fdbecaa9aba005d5690e4',
                  value: 1,
                  name: "La température de l'eau",
                  diagnosticInfos: [],
                  icons: [],
                  good: false,
                },
                {
                  _id: '5d6fdbecaa9aba005d5690e3',
                  value: 2,
                  name: 'La température des coquilles',
                  diagnosticInfos: [],
                  icons: [],
                  good: true,
                },
                {
                  _id: '5d6fdbecaa9aba005d5690e2',
                  value: 3,
                  name:
                    "La température dans l'oeuf et à l'extérieur de celui-ci",
                  diagnosticInfos: [],
                  icons: [],
                  good: true,
                },
              ],
              gapFill: {
                gaps: [],
              },
              swipeCards: {
                cards: [],
                choices: [],
              },
              slots: [],
              audios: [],
              icons: [],
              contentType: 'text',
              type: 'multiple',
            },
          ],
          random: false,
          keyName: 'exitQuiz',
        },
        iconsPreview: [],
        contentPages: [
          {
            _id: '5d6fdbecaa9aba005d5690eb',
            name: "Vitesse de l'air",
            icons: [],
            slideshow: [],
            audio: [],
            video: [],
            flashCards: [
              {
                _id: '5d6fdbecaa9aba005d5690ec',
                backContent: {
                  text:
                    'Le « transfert de chaleur par convection », prouve que la vitesse de l’air peut avoir une incidence significative sur la température des coquilles. ',
                  images: [],
                },
                frontContent: {
                  text: "Température et vitesse de l'air",
                  images: [],
                },
              },
            ],
            type: 'flashCards',
          },
          {
            _id: '5d6fdbecaa9aba005d5690e9',
            name: "Placement de l'oeuf",
            icons: [],
            slideshow: [],
            audio: [],
            video: [],
            flashCards: [
              {
                _id: '5d6fdbecaa9aba005d5690ea',
                backContent: {
                  text:
                    'Les œufs situés à proximité du ventilateur de mélange central, par exemple, seront soumis à une convection légèrement plus efficace.',
                  images: [],
                },
                frontContent: {
                  text: "Placement de l'oeuf dans l'incubateur",
                  images: [],
                },
              },
            ],
            type: 'flashCards',
          },
        ],
        icons: [],
        slideshow: [],
        audio: [],
        video: [],
        flashCards: [
          {
            _id: '5d6fdbecaa9aba005d5690ed',
            backContent: {
              text:
                'Les œufs incubés procèdent constamment à un échange de chaleur avec le micro-environnement alentour. ',
              images: [
                {
                  _id: '5d6fdbecaa9aba005d5690f7',
                  size: 15403,
                  container: 'filestack.eu.bdz',
                  filename: 'eggies.jpeg',
                  mimetype: 'image/jpeg',
                  url: 'https://cdn.filestackcontent.com/710sbim0QVaSpA78CPdj',
                  key:
                    'beedeez/5d6cc8d628bb31001ad2b939/lessons/5d6fc5b2e442c90044234c92',
                  type: 'original',
                },
                {
                  _id: '5d6fdbecaa9aba005d5690f6',
                  container: 'filestack.eu.bdz',
                  filename: 'eggies.jpg',
                  key: 'mxHN2B2NSZaVZilwRVAA_eggies.jpg',
                  size: 75753,
                  url: 'https://cdn.filestackcontent.com/y63JUzGrTUuaPepRBWpH',
                  mimetype: 'image/jpeg',
                  type: 'site',
                },
                {
                  _id: '5d6fdbecaa9aba005d5690f5',
                  container: 'filestack.eu.bdz',
                  filename: 'eggies.jpg',
                  key: 'PcxU97LqRLYSTKlZTes2_eggies.jpg',
                  size: 29714,
                  url: 'https://cdn.filestackcontent.com/xXa95o0Q67k4cEhAKlBQ',
                  mimetype: 'image/jpeg',
                  type: 'site-low-res',
                },
                {
                  _id: '5d6fdbecaa9aba005d5690f4',
                  container: 'filestack.eu.bdz',
                  filename: 'eggies.jpg',
                  key: 'fgwQwfBPTR2PtGc48h4Q_eggies.jpg',
                  size: 14905,
                  url: 'https://cdn.filestackcontent.com/9jHlmXBRnEqFNwTBSzg4',
                  mimetype: 'image/jpeg',
                  type: 'mobile',
                },
                {
                  _id: '5d6fdbecaa9aba005d5690f3',
                  container: 'filestack.eu.bdz',
                  filename: 'eggies.jpg',
                  key: 'tq8ZliT5OUzYCRkFnrAA_eggies.jpg',
                  size: 2335,
                  url: 'https://cdn.filestackcontent.com/u5ryjc1Rtixk1PGDxdd7',
                  mimetype: 'image/jpeg',
                  type: 'small',
                },
              ],
            },
            frontContent: {
              text: "Echange de chaleur avec le micro-environnement de l'oeuf",
              images: [
                {
                  _id: '5d6fdbecaa9aba005d5690f2',
                  size: 15165,
                  container: 'filestack.eu.bdz',
                  filename: 'eggies.jpeg',
                  mimetype: 'image/jpeg',
                  url: 'https://cdn.filestackcontent.com/OEwPB5c5QVifwiskW8ag',
                  key:
                    'beedeez/5d6cc8d628bb31001ad2b939/lessons/5d6fc5b2e442c90044234c92',
                  type: 'original',
                },
                {
                  _id: '5d6fdbecaa9aba005d5690f1',
                  container: 'filestack.eu.bdz',
                  filename: 'eggies.jpg',
                  key: 'oXGAWv51QU6SbssGane1_eggies.jpg',
                  size: 75172,
                  url: 'https://cdn.filestackcontent.com/HSP01pQuO76jl3ivovzw',
                  mimetype: 'image/jpeg',
                  type: 'site',
                },
                {
                  _id: '5d6fdbecaa9aba005d5690f0',
                  container: 'filestack.eu.bdz',
                  filename: 'eggies.jpg',
                  key: 'D34JRz3TEm8SjxwkCjQO_eggies.jpg',
                  size: 29488,
                  url: 'https://cdn.filestackcontent.com/nyoOX2chStWpdKlHcRKm',
                  mimetype: 'image/jpeg',
                  type: 'site-low-res',
                },
                {
                  _id: '5d6fdbecaa9aba005d5690ef',
                  container: 'filestack.eu.bdz',
                  filename: 'eggies.jpg',
                  key: 'jfiYPGXT5aOBcRO4Uc9l_eggies.jpg',
                  size: 14728,
                  url: 'https://cdn.filestackcontent.com/E4Ld92gLQw6xTlksTRSW',
                  mimetype: 'image/jpeg',
                  type: 'mobile',
                },
                {
                  _id: '5d6fdbecaa9aba005d5690ee',
                  container: 'filestack.eu.bdz',
                  filename: 'eggies.jpg',
                  key: 'rpvVCXFT5GT5pMWtlBnq_eggies.jpg',
                  size: 2333,
                  url: 'https://cdn.filestackcontent.com/iiKFZuylT72cEEJpbg3l',
                  mimetype: 'image/jpeg',
                  type: 'small',
                },
              ],
            },
          },
        ],
        type: 'flashCards',
      },
      {
        mainTitle: 'Incubateur Petersime à configuration en spirale',
        description: 'Quand les lois de la physique se lient au procédé.',
        _id: '5d6fdbecaa9aba005d5690d2',
        contentDraftRawContent: {
          blocks: [
            {
              key: '13sll',
              text:
                "Dans tout espace tridimensionnel, tel qu'un incubateur, une vitesse de l'air accrue entraîne un échange de chaleur par convection supérieur. Dans les incubateurs Petersime, la conception avancée des pales de ventilateur conduit à une distribution en spirale de la circulation d'air au sein de la machine. Selon que les éléments de refroidissement ou de chauffage à proximité du ventilateur sont activés ou non, cette circulation d'air en spirale réduit la hausse ou la baisse de la température à un minimum dans différentes positions dans l'incubateur.",
              type: 'unstyled',
              depth: 0,
              inlineStyleRanges: [
                {
                  offset: 56,
                  length: 84,
                  style: 'BOLD',
                },
                {
                  offset: 250,
                  length: 55,
                  style: 'BOLD',
                },
                {
                  offset: 411,
                  length: 95,
                  style: 'BOLD',
                },
              ],
              entityRanges: [],
            },
          ],
        },
        content:
          "Dans tout espace tridimensionnel, tel qu'un incubateur, **une vitesse de l'air accrue entraîne un échange de chaleur par convection supérieur.** Dans les incubateurs Petersime, la conception avancée des pales de ventilateur conduit à une distribution en **spirale de la circulation d'air au sein de la machine.** Selon que les éléments de refroidissement ou de chauffage à proximité du ventilateur sont activés ou non, **cette circulation d'air en spirale réduit la hausse ou la baisse de la température à un minimum** dans différentes positions dans l'incubateur.",
        validationThreshold: 0.8,
        name: "Comment fonctionne l'Incubateur Petersime",
        points: 0,
        overrideDuration: 4,
        entryQuizz: {
          type: 'question-list',
          isPositioningQuiz: false,
          diagnostic: {
            axes: [],
            themes: [],
          },
          lifeNumber: 1,
          questions: [
            {
              _id: '5d6fdbecaa9aba005d5690dd',
              title:
                "Selon vous, le sens de circulation de l'air n'a pas d'impact sur l'échange de chaleur.",
              explanationIsCompulsory: false,
              survey: false,
              choices: [
                {
                  _id: '5d6fdbecaa9aba005d5690df',
                  value: 0,
                  diagnosticInfos: [],
                  icons: [],
                  good: false,
                },
                {
                  _id: '5d6fdbecaa9aba005d5690de',
                  value: 1,
                  diagnosticInfos: [],
                  icons: [],
                  good: true,
                },
              ],
              gapFill: {
                gaps: [],
              },
              swipeCards: {
                cards: [],
                choices: [],
              },
              slots: [],
              audios: [],
              icons: [],
              contentType: 'text',
              type: 'truefalse',
            },
          ],
          random: false,
          keyName: 'exitQuiz',
        },
        quizz: {
          type: 'survey',
          diagnostic: {
            axes: [],
            themes: [],
          },
          lifeNumber: 1,
          questions: [],
          random: false,
          keyName: 'exitQuiz',
        },
        iconsPreview: [],
        contentPages: [
          {
            _id: '5d6fdbecaa9aba005d5690d6',
            contentDraftRawContent: {
              blocks: [
                {
                  key: '373s0',
                  text:
                    "Mais ce n'est pas tout, puisque le retournement des œufs joue également un rôle déterminant en matière d'échange de chaleur. Outre l'importance jouée sur le plan physiologique (positionnement de l'embryon, vascularisation bilatérale et utilisation du sac vitellin), cette technique optimise la dynamique de la circulation d'air au sein de l'incubateur de manière symétrique. Grâce à une alternance régulière des positions de rotation des casiers entre les profils en \"A\" et en \"V\", le passage du flux d'air à travers les œufs convient davantage par rapport à une position horizontale.",
                  type: 'unstyled',
                  depth: 0,
                  inlineStyleRanges: [
                    {
                      offset: 32,
                      length: 92,
                      style: 'BOLD',
                    },
                    {
                      offset: 266,
                      length: 109,
                      style: 'BOLD',
                    },
                  ],
                  entityRanges: [],
                },
              ],
            },
            content:
              "Mais ce n'est pas tout, puisque **le retournement des œufs joue également un rôle déterminant en matière d'échange de chaleur.** Outre l'importance jouée sur le plan physiologique (positionnement de l'embryon, vascularisation bilatérale et utilisation du sac vitellin), **cette technique optimise la dynamique de la circulation d'air au sein de l'incubateur de manière symétrique.** Grâce à une alternance régulière des positions de rotation des casiers entre les profils en \"A\" et en \"V\", le passage du flux d'air à travers les œufs convient davantage par rapport à une position horizontale.",
            name: 'Incubateur Petersime',
            iconCredits: '',
            icons: [
              {
                _id: '5d6fdbecaa9aba005d5690db',
                size: 10204,
                container: 'filestack.eu.bdz',
                filename: 'Incubateur rota casier.jpeg',
                mimetype: 'image/jpeg',
                url: 'https://cdn.filestackcontent.com/wF9o6NsmSxusxkrDJ9l2',
                key:
                  'beedeez/5d6cc8d628bb31001ad2b939/lessons/5d6fc5b2e442c90044234c92',
                type: 'original',
              },
              {
                _id: '5d6fdbecaa9aba005d5690da',
                container: 'filestack.eu.bdz',
                filename: 'Incubateur rota casier.jpg',
                key: 'aZ5Ocb54RSFtnaSlKgv3_Incubateur rota casier.jpg',
                size: 63396,
                url: 'https://cdn.filestackcontent.com/k9vH3qlQTrCAvfzfcHPv',
                mimetype: 'image/jpeg',
                type: 'site',
              },
              {
                _id: '5d6fdbecaa9aba005d5690d9',
                container: 'filestack.eu.bdz',
                filename: 'Incubateur rota casier.jpg',
                key: 'zdNZMHwGQHniHj6FEbcQ_Incubateur rota casier.jpg',
                size: 25154,
                url: 'https://cdn.filestackcontent.com/1aAy5zmNQMSrJCrkrWcZ',
                mimetype: 'image/jpeg',
                type: 'site-low-res',
              },
              {
                _id: '5d6fdbecaa9aba005d5690d8',
                container: 'filestack.eu.bdz',
                filename: 'Incubateur rota casier.jpg',
                key: 'kveWP0pIQrmN7DQn0lYr_Incubateur rota casier.jpg',
                size: 12035,
                url: 'https://cdn.filestackcontent.com/1NqI4MKVQnCQ5WBu8v28',
                mimetype: 'image/jpeg',
                type: 'mobile',
              },
              {
                _id: '5d6fdbecaa9aba005d5690d7',
                container: 'filestack.eu.bdz',
                filename: 'Incubateur rota casier.jpg',
                key: 'LuzEbCjzQcm9RhiS02sY_Incubateur rota casier.jpg',
                size: 1797,
                url: 'https://cdn.filestackcontent.com/ubMW80HWSQ6Q9e8rXHjX',
                mimetype: 'image/jpeg',
                type: 'small',
              },
            ],
            slideshow: [],
            audio: [],
            video: [],
            flashCards: [],
            type: 'standard',
          },
        ],
        icons: [],
        slideshow: [],
        audio: [],
        video: [
          {
            _id: '5d6fdbecaa9aba005d5690e0',
            type: 'youtube',
            value: 'gBlHMGgkLIs',
            videoMetaData: {
              assets: [],
              timeline: [],
              filters: [],
              overlays: [],
            },
          },
        ],
        flashCards: [
          {
            _id: '5d6fdbecaa9aba005d5690dc',
            backContent: {
              text: '',
              images: [],
            },
            frontContent: {
              text: '',
              images: [],
            },
          },
        ],
        type: 'video',
      },
      {
        mainTitle: "Circulation de l'air entre les casiers",
        description: '',
        _id: '5d6fdbecaa9aba005d5690b6',
        contentDraftRawContent: {
          blocks: [
            {
              key: '94tjm',
              text:
                "À ce stade, il apparaît évident que l'échange de chaleur entre l'œuf et son micro-environnement alentour est en constante évolution pendant l'incubation. Jusqu'ici, la surveillance de la température des coquilles constitue la technique la plus pratique pour suivre les pertes/gains de chaleur liés à l'environnement de l'incubateur.\nC'est pourquoi les incubateurs Petersime sont équipés de la technologie OvoScan™. Cette dernière permet d'ajuster automatiquement la température de l'environnement en mesurant la température des coquilles.",
              type: 'unstyled',
              depth: 0,
              inlineStyleRanges: [
                {
                  offset: 36,
                  length: 117,
                  style: 'BOLD',
                },
                {
                  offset: 379,
                  length: 35,
                  style: 'BOLD',
                },
              ],
              entityRanges: [],
            },
            {
              key: '2a533',
              text: '',
              type: 'unstyled',
              depth: 0,
              inlineStyleRanges: [],
              entityRanges: [],
            },
            {
              key: '5hifm',
              text:
                "OvoScan™ : création de l'environnement optimal pour chaque lot d'œufs, quels que soient la taille, l'âge et les caractéristiques génétiques des œufs à couver",
              type: 'unstyled',
              depth: 0,
              inlineStyleRanges: [],
              entityRanges: [],
            },
          ],
        },
        content:
          "À ce stade, il apparaît évident que **l'échange de chaleur entre l'œuf et son micro-environnement alentour est en constante évolution pendant l'incubation.** Jusqu'ici, la surveillance de la température des coquilles constitue la technique la plus pratique pour suivre les pertes/gains de chaleur liés à l'environnement de l'incubateur.\nC'est pourquoi les incubateurs Petersime sont **équipés de la technologie OvoScan™.** Cette dernière permet d'ajuster automatiquement la température de l'environnement en mesurant la température des coquilles.\n\n\nOvoScan™ : création de l'environnement optimal pour chaque lot d'œufs, quels que soient la taille, l'âge et les caractéristiques génétiques des œufs à couver",
        name: "Flow d'air entre les casiers",
        iconCredits: '',
        entryQuizz: {
          type: 'question-list',
          isPositioningQuiz: true,
          diagnostic: {
            axes: [],
            themes: [],
          },
          lifeNumber: 1,
          questions: [],
          random: false,
          keyName: 'exitQuiz',
        },
        quizz: {
          type: 'question-list',
          diagnostic: {
            axes: [],
            themes: [],
          },
          lifeNumber: 1,
          questions: [
            {
              _id: '5d6fdbecaa9aba005d5690c1',
              explanationIsCompulsory: false,
              survey: false,
              choices: [],
              gapFill: {
                text:
                  'Les incubateurs à chargement unique professionnels sont directement capables d’accueillir des $[gap-start](ck05f70xs002k046oocrryj4d)[gap-end] d’œufs. De telles quantités impliquent souvent le mélange d’œufs aux caractéristiques $[gap-start](ck05f7ubj002l046ongi16td3)[gap-end].',
                gaps: [
                  {
                    _id: '5d6fdbecaa9aba005d5690c7',
                    tag: 'ck05f70xs002k046oocrryj4d',
                    type: 'wordset',
                    choices: [
                      {
                        _id: '5d6fdbecaa9aba005d5690cb',
                        label: 'milliers',
                        value: 0,
                        good: true,
                      },
                      {
                        _id: '5d6fdbecaa9aba005d5690ca',
                        label: 'embryons',
                        value: 1,
                        good: false,
                      },
                      {
                        _id: '5d6fdbecaa9aba005d5690c9',
                        label: 'tonnes',
                        value: 2,
                        good: false,
                      },
                      {
                        _id: '5d6fdbecaa9aba005d5690c8',
                        label: 'centaines',
                        value: 3,
                        good: false,
                      },
                    ],
                  },
                  {
                    _id: '5d6fdbecaa9aba005d5690c2',
                    tag: 'ck05f7ubj002l046ongi16td3',
                    type: 'wordset',
                    choices: [
                      {
                        _id: '5d6fdbecaa9aba005d5690c6',
                        label: 'caractérielles',
                        value: 0,
                        good: false,
                      },
                      {
                        _id: '5d6fdbecaa9aba005d5690c5',
                        label: 'équivalentes',
                        value: 1,
                        good: false,
                      },
                      {
                        _id: '5d6fdbecaa9aba005d5690c4',
                        label: 'distinctes',
                        value: 2,
                        good: true,
                      },
                      {
                        _id: '5d6fdbecaa9aba005d5690c3',
                        label: 'inégales',
                        value: 3,
                        good: false,
                      },
                    ],
                  },
                ],
              },
              swipeCards: {
                cards: [],
                choices: [],
              },
              slots: [],
              audios: [],
              icons: [],
              contentType: 'text',
              type: 'gap-fill',
            },
            {
              _id: '5d6fdbecaa9aba005d5690b7',
              explanationIsCompulsory: false,
              survey: false,
              choices: [
                {
                  _id: '5d6fdbecaa9aba005d5690b9',
                  value: 0,
                  diagnosticInfos: [],
                  icons: [],
                  good: false,
                },
                {
                  _id: '5d6fdbecaa9aba005d5690b8',
                  value: 1,
                  diagnosticInfos: [],
                  icons: [],
                  good: false,
                },
              ],
              gapFill: {
                gaps: [],
              },
              swipeCards: {
                cards: [
                  {
                    _id: '5d6fdbecaa9aba005d5690c0',
                    name: "Le sens de circulation de l'air",
                    contentType: 'text',
                    icons: [],
                    choice: 0,
                  },
                  {
                    _id: '5d6fdbecaa9aba005d5690bf',
                    name: "L'hydrométrie",
                    contentType: 'text',
                    icons: [],
                    choice: 1,
                  },
                  {
                    _id: '5d6fdbecaa9aba005d5690be',
                    name: "L'orientation des casiers",
                    contentType: 'text',
                    icons: [],
                    choice: 0,
                  },
                  {
                    _id: '5d6fdbecaa9aba005d5690bd',
                    name: 'La prise de température des coquilles',
                    contentType: 'text',
                    icons: [],
                    choice: 0,
                  },
                  {
                    _id: '5d6fdbecaa9aba005d5690bc',
                    name: 'La classification par la taille de la coquille',
                    contentType: 'text',
                    icons: [],
                    choice: 1,
                  },
                ],
                choices: [
                  {
                    _id: '5d6fdbecaa9aba005d5690bb',
                    value: 0,
                    label: "Géré pas l'incubateur peterisme",
                  },
                  {
                    _id: '5d6fdbecaa9aba005d5690ba',
                    value: 1,
                    label: "N'est pas géré par l'incubateur peterisme",
                  },
                ],
              },
              slots: [],
              audios: [],
              icons: [],
              contentType: 'text',
              type: 'swipecards',
            },
            {
              _id: '5d6fddd2a3121f0080335156',
              title: 'Où se situe le dispositif OvoScan',
              allowedAttempt: 3,
              explanationIsCompulsory: false,
              survey: false,
              choices: [
                {
                  _id: '5d6fddd2a3121f0080335157',
                  value: 0,
                  name: 'Boitier OvoScan',
                  diagnosticInfos: [],
                  position: {
                    height: 381.8181818181818,
                    width: 381.8181818181818,
                    left: 1328.1818181818182,
                    top: 1410,
                  },
                  icons: [],
                  good: true,
                },
              ],
              gapFill: {
                gaps: [],
              },
              swipeCards: {
                cards: [],
                choices: [],
              },
              slots: [],
              audios: [],
              icons: [
                {
                  key:
                    'beedeez/5d6cc8d628bb31001ad2b939/lessons/5d6fc5b2e442c90044234c92',
                  url: 'https://cdn.filestackcontent.com/wvHi5AbQ9GFemVq45ucQ',
                  mimetype: 'image/jpeg',
                  filename: 'OvoScan.jpeg',
                  container: 'filestack.eu.bdz',
                  size: 12297,
                  _id: '5d6fddd2a3121f008033515c',
                  type: 'original',
                },
                {
                  mimetype: 'image/jpeg',
                  url: 'https://cdn.filestackcontent.com/2aolZDyQpOV7ZhIZ3RQ4',
                  size: 149311,
                  key: 'jrDWCDPgQWiSsCdQ9Kta_OvoScan.jpg',
                  filename: 'OvoScan.jpg',
                  container: 'filestack.eu.bdz',
                  _id: '5d6fddd2a3121f008033515b',
                  type: 'site',
                },
                {
                  mimetype: 'image/jpeg',
                  url: 'https://cdn.filestackcontent.com/SIDOW4gTW6GR7maOXkgQ',
                  size: 56033,
                  key: '7XpN22QTUSwLY3CnCygg_OvoScan.jpg',
                  filename: 'OvoScan.jpg',
                  container: 'filestack.eu.bdz',
                  _id: '5d6fddd2a3121f008033515a',
                  type: 'site-low-res',
                },
                {
                  mimetype: 'image/jpeg',
                  url: 'https://cdn.filestackcontent.com/d5GYnfljSPeGBZishpG3',
                  size: 29171,
                  key: 'RcJhQypDQKWvpIArgupg_OvoScan.jpg',
                  filename: 'OvoScan.jpg',
                  container: 'filestack.eu.bdz',
                  _id: '5d6fddd2a3121f0080335159',
                  type: 'mobile',
                },
                {
                  mimetype: 'image/jpeg',
                  url: 'https://cdn.filestackcontent.com/NipET36SSlehfph3aqLz',
                  size: 3232,
                  key: 'cTRNmqFsSlmqf7ab4ZVB_OvoScan.jpg',
                  filename: 'OvoScan.jpg',
                  container: 'filestack.eu.bdz',
                  _id: '5d6fddd2a3121f0080335158',
                  type: 'small',
                },
              ],
              contentType: 'text',
              type: 'image-map',
            },
          ],
          random: false,
          keyName: 'exitQuiz',
        },
        iconsPreview: [],
        contentPages: [],
        icons: [
          {
            _id: '5d6fdbecaa9aba005d5690d1',
            size: 26294,
            container: 'filestack.eu.bdz',
            filename: 'Air flow casiers.png',
            mimetype: 'image/png',
            url: 'https://cdn.filestackcontent.com/nKhWVzSR066vHtTWfd5z',
            key:
              'beedeez/5d6cc8d628bb31001ad2b939/lessons/5d6fc5b2e442c90044234c92',
            type: 'original',
          },
          {
            _id: '5d6fdbecaa9aba005d5690d0',
            container: 'filestack.eu.bdz',
            filename: 'Air flow casiers.png',
            key: 'o9UY6ijxTmKpa8VE0mp6_Air flow casiers.png',
            size: 211589,
            url: 'https://cdn.filestackcontent.com/BojNrUNTJi1YEpqESyLN',
            mimetype: 'image/png',
            type: 'site',
          },
          {
            _id: '5d6fdbecaa9aba005d5690cf',
            container: 'filestack.eu.bdz',
            filename: 'Air flow casiers.png',
            key: 'DTHUNmRESYeJUZf1eugp_Air flow casiers.png',
            size: 75855,
            url: 'https://cdn.filestackcontent.com/WoaL3RUwScqMaY5q9BBw',
            mimetype: 'image/png',
            type: 'site-low-res',
          },
          {
            _id: '5d6fdbecaa9aba005d5690ce',
            container: 'filestack.eu.bdz',
            filename: 'Air flow casiers.png',
            key: 'TP5jAAbkTObRkCCIo4kQ_Air flow casiers.png',
            size: 34721,
            url: 'https://cdn.filestackcontent.com/72VYvMYTPWDw8aF3nqHn',
            mimetype: 'image/png',
            type: 'mobile',
          },
          {
            _id: '5d6fdbecaa9aba005d5690cd',
            container: 'filestack.eu.bdz',
            filename: 'Air flow casiers.png',
            key: 'ka2j7FIxR7SifffSSlR5_Air flow casiers.png',
            size: 5221,
            url: 'https://cdn.filestackcontent.com/cm9NYwpaRtotnqEzI4ig',
            mimetype: 'image/png',
            type: 'small',
          },
        ],
        slideshow: [],
        audio: [],
        video: [],
        flashCards: [
          {
            _id: '5d6fdbecaa9aba005d5690cc',
            backContent: {
              text: '',
              images: [],
            },
            frontContent: {
              text: '',
              images: [],
            },
          },
        ],
        type: 'standard',
      },
    ],
    metrics: {
      ratings: 1,
      view: 3,
      share: 0,
      like: 0,
      score: 5,
    },
    icons: [],
    _accessingUserGroupIds: [],
    _accessingTrackIds: ['5d70d156547c3f002708ecd0'],
    _trackOrganization: [],
    sources: [],
    images: [
      {
        key:
          'beedeez/5d6cc8d628bb31001ad2b939/lessons/5d6fc5b2e442c90044234c92',
        url: 'https://cdn.filestackcontent.com/IempssvsQoGTkXicpFEJ',
        mimetype: 'image/jpeg',
        filename: 'cidape logo.jpeg',
        container: 'filestack.eu.bdz',
        size: 5122,
        _id: '5d6fdf8c0ca7420076c96225',
        type: 'original',
      },
      {
        mimetype: 'image/jpeg',
        url: 'https://cdn.filestackcontent.com/FjK2a2gQQyJQp3OGTPZX',
        size: 60334,
        key: 'sqyeDFlRci88XMWlQphg_cidape logo.jpg',
        filename: 'cidape logo.jpg',
        container: 'filestack.eu.bdz',
        _id: '5d6fdf8c0ca7420076c96224',
        type: 'site',
      },
      {
        mimetype: 'image/jpeg',
        url: 'https://cdn.filestackcontent.com/fe7C3eZlQUycmRES7M6N',
        size: 21903,
        key: 'bgEKxmzuTweV4f7Laqoj_cidape logo.jpg',
        filename: 'cidape logo.jpg',
        container: 'filestack.eu.bdz',
        _id: '5d6fdf8c0ca7420076c96223',
        type: 'site-low-res',
      },
      {
        mimetype: 'image/jpeg',
        url: 'https://cdn.filestackcontent.com/jlUIj0LuSfqV58qFsA1S',
        size: 11030,
        key: '3EROzxE0QHq5XnNNJU7v_cidape logo.jpg',
        filename: 'cidape logo.jpg',
        container: 'filestack.eu.bdz',
        _id: '5d6fdf8c0ca7420076c96222',
        type: 'mobile',
      },
      {
        mimetype: 'image/jpeg',
        url: 'https://cdn.filestackcontent.com/VfYDDPWBQcabZiIMscv7',
        size: 1989,
        key: 'DIUxWWojTXObLDLbRrkO_cidape logo.jpg',
        filename: 'cidape logo.jpg',
        container: 'filestack.eu.bdz',
        _id: '5d6fdf8c0ca7420076c96221',
        type: 'small',
      },
    ],
    links: [],
    _id: '5d70d1077584f50038aea686',
  },
  {
    title: 'B.A.BA de la poésie',
    summary:
      'Vous ne savez plus ce qu\'est un alexandrin ou un sonnet, ni si on compte le "e" muet à la fin d\'un vers ? Voici un petit rappel des bases incontournables de la poésie.',
    creationDate: '2019-05-13T09:06:50.778Z',
    lastUpdate: '2019-05-13T09:06:50.778Z',
    featuredDate: null,
    type: 'digital-beedeez',
    status: 'online',
    level: 'beginning',
    category: '5cd933aa659dfc0050008737',
    categories: ['5cd933aa659dfc0050008737'],
    lang: 'fr',
    maxRetry: 1,
    playMode: 'standard',
    forumDisable: false,
    barcodes: [],
    chapters: [
      {
        name: 'Le vocabulaire poétique de base',
        content:
          'Un poème se structure en STROPHES, elles-mêmes formées de plusieurs VERS, eux-mêmes décomposés en SYLLABES.\n\nSelon le nombre de vers qu’elles comportent, les strophes sont nommées : \n. Tercet pour les strophes à 3 vers\n. Quatrain pour 4 vers\n. Quintil pour 5 vers\n. Sizin pour 6 vers\n. Septain pour 7 vers (plus rare)\n. Huitain pour 8 vers\n. Neuvain pour 9 vers (plus rare également)\n. Dizain pour 10 vers\n\nLes vers comportent fréquemment un nombre de syllabes pair, et sont ainsi désignés :\n. Un vers à 6 syllabes est un hexasyllabe,\n. Un vers à 8 syllabes un octosyllabe,\n. A 10 syllabes un décasyllabe,\n. A 12 syllabes il s’agit du célèbre ALEXANDRIN, sans doute le format de vers le plus classique.\n\nLes vers longs se composent souvent de deux HÉMISTICHES, c’est-à-dire deux moitiés de vers, scindées par ce qu’on appelle une CÉSURE et qui désigne donc le milieu du vers. La césure confère un rythme binaire au vers en suggérant une pause dans la lecture, qui peut être virtuelle ou marquée par une ponctuation.\nAinsi dans la partie XXII de « Spleen et Idéal » de Baudelaire :\n« Je t’adore à l’égal de la voûte nocturne,\nÔ vase de tristesse, ô grande taciturne, »\nDans le 1er vers, la césure après « égal » est suggérée, tandis qu’elle est dans le 2nd vers marquée par la virgule après « tristesse ».',
        _id: '55a78723b400730300932cdb',
        entryQuizz: {
          isPositioningQuiz: true,
          diagnostic: {
            axes: [],
            themes: [],
          },
          lifeNumber: 1,
          questions: [
            {
              title: 'Un alexandrin est un vers à :',
              _id: '55a78723b400730300932cdc',
              points: 1,
              explanationIsCompulsory: false,
              survey: false,
              choices: [
                {
                  name: '5 syllabes',
                  value: 0,
                  _id: '55a78723b400730300932ce0',
                  diagnosticInfos: [],
                  icons: [],
                  good: false,
                },
                {
                  name: '6 syllabes',
                  value: 1,
                  _id: '55a78723b400730300932cdf',
                  diagnosticInfos: [],
                  icons: [],
                  good: false,
                },
                {
                  name: '8 syllabes',
                  value: 2,
                  _id: '55a78723b400730300932cde',
                  diagnosticInfos: [],
                  icons: [],
                  good: false,
                },
                {
                  name: '12 syllabes',
                  value: 3,
                  _id: '55a78723b400730300932cdd',
                  diagnosticInfos: [],
                  icons: [],
                  good: true,
                },
              ],
              gapFill: {
                gaps: [],
              },
              swipeCards: {
                cards: [],
                choices: [],
              },
              slots: [],
              audios: [],
              icons: [],
              contentType: 'text',
              type: 'simple',
            },
          ],
          random: false,
          keyName: 'entryQuizz',
        },
        quizz: {
          diagnostic: {
            axes: [],
            themes: [],
          },
          lifeNumber: 1,
          questions: [
            {
              title: "Les deux hémistiches d'un vers sont séparés par une :",
              _id: '55a78723b400730300932ce1',
              points: 1,
              explanationIsCompulsory: false,
              survey: false,
              choices: [
                {
                  name: 'Sciure',
                  value: 0,
                  _id: '55a78723b400730300932ce5',
                  diagnosticInfos: [],
                  icons: [],
                  good: false,
                },
                {
                  name: 'Cisaille',
                  value: 1,
                  _id: '55a78723b400730300932ce4',
                  diagnosticInfos: [],
                  icons: [],
                  good: false,
                },
                {
                  name: 'Césure',
                  value: 2,
                  _id: '55a78723b400730300932ce3',
                  diagnosticInfos: [],
                  icons: [],
                  good: true,
                },
                {
                  name: 'Virgule',
                  value: 3,
                  _id: '55a78723b400730300932ce2',
                  diagnosticInfos: [],
                  icons: [],
                  good: false,
                },
              ],
              gapFill: {
                gaps: [],
              },
              swipeCards: {
                cards: [],
                choices: [],
              },
              slots: [],
              audios: [],
              icons: [],
              contentType: 'text',
              type: 'simple',
            },
          ],
          random: false,
          keyName: 'exitQuizz',
        },
        iconsPreview: [],
        contentPages: [],
        icons: [
          {
            _id: '55a789b0b400730300932cf9',
            url: 'https://www.filepicker.io/api/file/WPZxhawSS7OPMoTikBRT',
            filename: 'abc-390026_640.jpg',
            mimetype: 'image/jpeg',
            size: 9463,
            key:
              'beedeez/dev/lessons/site/rgqsG8FuT0qa3hCBPCO0_abc-390026_640.jpg',
            type: 'site',
          },
          {
            _id: '55a789b0b400730300932cf8',
            url: 'https://www.filepicker.io/api/file/UkqOezFRAuN6iMbzWScg',
            filename: 'abc-390026_640.jpg',
            mimetype: 'image/jpeg',
            size: 9463,
            key:
              'beedeez/dev/lessons/mobile/VM3jr6PDQp6yNbjlcc2K_abc-390026_640.jpg',
            type: 'mobile',
          },
          {
            _id: '55a789b0b400730300932cf7',
            url: 'https://www.filepicker.io/api/file/13OZ4j7rQEmajDyb6c0C',
            filename: 'abc-390026_640.jpg',
            mimetype: 'image/jpeg',
            size: 1141,
            key:
              'beedeez/dev/lessons/small/eMPZ40pSzDT8nD87mMxw_abc-390026_640.jpg',
            type: 'small',
          },
          {
            _id: '55a789b0b400730300932cf6',
            url: 'https://www.filepicker.io/api/file/Yciu0V7xQYSpSXqfa8Lb',
            filename: 'abc-390026_640.jpg',
            mimetype: 'image/jpeg',
            size: 648,
            key:
              'beedeez/dev/lessons/tiny/YkWffRv2ArDFvcKaeQnG_abc-390026_640.jpg',
            type: 'tiny',
          },
          {
            _id: '55a789b0b400730300932cf5',
            url: 'https://www.filepicker.io/api/file/k5UDTqtWRrCjcTQ6Rq0c',
            filename: 'abc-390026_640.jpg',
            mimetype: 'image/jpeg',
            size: 70340,
            key:
              'beedeez/dev/lessons/img/GvfvugAzRoWwShMYqrsu_abc-390026_640.jpg',
            container: 'followus-dev',
            type: 'original',
          },
        ],
        slideshow: [],
        audio: [],
        video: [],
        flashCards: [],
        type: 'standard',
      },
      {
        name: 'Le décompte des syllabes',
        content:
          'Le nombre et la longueur des strophes sont des éléments primordiaux pour donner son rythme au poème, tout comme le décompte des syllabes de chaque vers.\n\nPOUR COMPTER LE NOMBRE DE SYLLABES, on prend garde à la règle qui s’applique au « e » muet : le « e » compte lorsqu’il est placé avant une consonne mais ne compte pas lorsqu’il est placé avant une voyelle ou en fin de vers.\nAinsi dans ces deux alexandrins du poème « A une femme » de Paul Verlaine :\n« A vous ces vers de par la grâce consolante\nDe vos grands yeux où rit et pleure un rêve doux, »\non compte 2 syllabes pour « grâce », 3 pour « consolante », 1 pour « pleure » et 2 pour « rêve ».\n\nFACE A UN MOT COMPORTANT 2 VOYELLES ASSOCIÉES, comme le mot « nuit » par exemple, le poète peut choisir :\n. soit de recourir au mode courant et de ne compter qu’1 seule syllabe, on parle alors de synérèse\n. soit de préférer une prononciation en 2 syllabes, en disant donc « nu-it », et l’on parle alors de diérèse.',
        _id: '55a78723b400730300932cd0',
        entryQuizz: {
          isPositioningQuiz: true,
          diagnostic: {
            axes: [],
            themes: [],
          },
          lifeNumber: 1,
          questions: [
            {
              title: 'En poésie, le mot « union » compte pour :',
              _id: '55a78723b400730300932cd1',
              points: 1,
              explanationIsCompulsory: false,
              survey: false,
              choices: [
                {
                  name: 'Toujours 2 syllabes',
                  value: 0,
                  _id: '55a78723b400730300932cd5',
                  diagnosticInfos: [],
                  icons: [],
                  good: false,
                },
                {
                  name: 'Toujours 3 syllabes',
                  value: 1,
                  _id: '55a78723b400730300932cd4',
                  diagnosticInfos: [],
                  icons: [],
                  good: false,
                },
                {
                  name: 'Parfois 2 syllabes, parfois 3',
                  value: 2,
                  _id: '55a78723b400730300932cd3',
                  diagnosticInfos: [],
                  icons: [],
                  good: true,
                },
                {
                  name: '4 syllabes',
                  value: 3,
                  _id: '55a78723b400730300932cd2',
                  diagnosticInfos: [],
                  icons: [],
                  good: false,
                },
              ],
              gapFill: {
                gaps: [],
              },
              swipeCards: {
                cards: [],
                choices: [],
              },
              slots: [],
              audios: [],
              icons: [],
              contentType: 'text',
              type: 'simple',
            },
          ],
          random: false,
          keyName: 'entryQuizz',
        },
        quizz: {
          diagnostic: {
            axes: [],
            themes: [],
          },
          lifeNumber: 1,
          questions: [
            {
              title: 'On compte une syllabe lorsqu’un « e » muet est placé :',
              _id: '55a78723b400730300932cd6',
              points: 1,
              explanationIsCompulsory: false,
              survey: false,
              choices: [
                {
                  name: 'Devant une consonne',
                  value: 0,
                  _id: '55a78723b400730300932cda',
                  diagnosticInfos: [],
                  icons: [],
                  good: true,
                },
                {
                  name: 'Devant une voyelle',
                  value: 1,
                  _id: '55a78723b400730300932cd9',
                  diagnosticInfos: [],
                  icons: [],
                  good: false,
                },
                {
                  name: 'En fin de vers',
                  value: 2,
                  _id: '55a78723b400730300932cd8',
                  diagnosticInfos: [],
                  icons: [],
                  good: false,
                },
                {
                  name: 'Au milieu du vers',
                  value: 3,
                  _id: '55a78723b400730300932cd7',
                  diagnosticInfos: [],
                  icons: [],
                  good: false,
                },
              ],
              gapFill: {
                gaps: [],
              },
              swipeCards: {
                cards: [],
                choices: [],
              },
              slots: [],
              audios: [],
              icons: [],
              contentType: 'text',
              type: 'simple',
            },
          ],
          random: false,
          keyName: 'exitQuizz',
        },
        iconsPreview: [],
        contentPages: [],
        icons: [
          {
            _id: '55a789b0b400730300932cf4',
            url: 'https://www.filepicker.io/api/file/lx8kJnkQOygxjbp3vtwI',
            filename: 'pay-530338_640.jpg',
            mimetype: 'image/jpeg',
            size: 12108,
            key:
              'beedeez/dev/lessons/site/ADpqsilrQwRtEO7XUKFL_pay-530338_640.jpg',
            type: 'site',
          },
          {
            _id: '55a789b0b400730300932cf3',
            url: 'https://www.filepicker.io/api/file/HvMkB30eSj6iVwdylHC2',
            filename: 'pay-530338_640.jpg',
            mimetype: 'image/jpeg',
            size: 12108,
            key:
              'beedeez/dev/lessons/mobile/BOCCUd2NR3mZlfOdZ2Gz_pay-530338_640.jpg',
            type: 'mobile',
          },
          {
            _id: '55a789b0b400730300932cf2',
            url: 'https://www.filepicker.io/api/file/YWM617pDQWqEfTCl8xLW',
            filename: 'pay-530338_640.jpg',
            mimetype: 'image/jpeg',
            size: 1592,
            key:
              'beedeez/dev/lessons/small/eAHUK6oTRdipGPF3Sghx_pay-530338_640.jpg',
            type: 'small',
          },
          {
            _id: '55a789b0b400730300932cf1',
            url: 'https://www.filepicker.io/api/file/FPbpIxHLRDepGTjGTQXQ',
            filename: 'pay-530338_640.jpg',
            mimetype: 'image/jpeg',
            size: 850,
            key:
              'beedeez/dev/lessons/tiny/u0v8yVrSPyGhRu2fPHHA_pay-530338_640.jpg',
            type: 'tiny',
          },
          {
            _id: '55a789b0b400730300932cf0',
            url: 'https://www.filepicker.io/api/file/cnPHdCRvRzCjLFGSS90w',
            filename: 'pay-530338_640.jpg',
            mimetype: 'image/jpeg',
            size: 74667,
            key:
              'beedeez/dev/lessons/img/W5pXcnytQ52QwT5aQysN_pay-530338_640.jpg',
            container: 'followus-dev',
            type: 'original',
          },
        ],
        slideshow: [],
        audio: [],
        video: [],
        flashCards: [],
        type: 'standard',
      },
      {
        name: 'Les rimes',
        content:
          "Les jeux de sonorités entre les mots placés à la fin des vers permettent de former des rimes. Grâce aux rimes, les vers s’associent entre eux, se répondent, se croisent, créant la mélodie du poème.\nPour schématiser l’organisation des rimes d’un poème, on désigne fréquemment leurs sonorités par les lettres A, B, C, D, E…\n\nLA RICHESSE DES RIMES est variable :\nLes rimes riches comportent au moins 3 sons en commun : ensemble / rassemble.\nLes rimes suffisantes comportent 2 sons en commun : orage / sage.\nLes rimes pauvres comportent 1 seul son commun : faux / maux.\n\nLA DISPOSITION DES RIMES joue aussi un rôle dans le rythme poétique :\nLes rimes plates, ou suivies, se succèdent selon le schéma AABB\nLes rimes croisées alternant en ABAB\nLes rimes embrassées dessinent le schéma ABBA\nOutre les rimes en fin de vers, on peut trouver également des rimes à l’intérieur des vers qui enrichissent la mélodie.\n\nEn se basant sur la répétition d’un son, les assonances (répétition d’un son voyelle) et allitérations (répétition d’un son consonne) contribuent également à la construction du poème. Ainsi Apollinaire joue-t-il par exemple avec une assonance en « ou » dans « Le pont Mirabeau » : \n«  Sous le pont Mirabeau coule la Seine\nEt nos amours\nFaut-il qu'il m'en souvienne\nLa joie venait toujours après la peine  »",
        _id: '55a78723b400730300932cc5',
        entryQuizz: {
          isPositioningQuiz: true,
          diagnostic: {
            axes: [],
            themes: [],
          },
          lifeNumber: 1,
          questions: [
            {
              title: 'Des rimes embrassées sont des rimes :',
              _id: '55a78723b400730300932cc6',
              points: 1,
              explanationIsCompulsory: false,
              survey: false,
              choices: [
                {
                  name: 'organisées en AABB',
                  value: 0,
                  _id: '55a78723b400730300932cca',
                  diagnosticInfos: [],
                  icons: [],
                  good: false,
                },
                {
                  name: 'organisées en ABAB',
                  value: 1,
                  _id: '55a78723b400730300932cc9',
                  diagnosticInfos: [],
                  icons: [],
                  good: false,
                },
                {
                  name: 'organisées en ABBA',
                  value: 2,
                  _id: '55a78723b400730300932cc8',
                  diagnosticInfos: [],
                  icons: [],
                  good: true,
                },
                {
                  name: 'organisées en AAAA',
                  value: 3,
                  _id: '55a78723b400730300932cc7',
                  diagnosticInfos: [],
                  icons: [],
                  good: false,
                },
              ],
              gapFill: {
                gaps: [],
              },
              swipeCards: {
                cards: [],
                choices: [],
              },
              slots: [],
              audios: [],
              icons: [],
              contentType: 'text',
              type: 'simple',
            },
          ],
          random: false,
          keyName: 'entryQuizz',
        },
        quizz: {
          diagnostic: {
            axes: [],
            themes: [],
          },
          lifeNumber: 1,
          questions: [
            {
              title: 'La confrontation des mots ravage / dérapage forme :',
              _id: '55a78723b400730300932ccb',
              points: 1,
              explanationIsCompulsory: false,
              survey: false,
              choices: [
                {
                  name: 'Une rime riche',
                  value: 0,
                  _id: '55a78723b400730300932ccf',
                  diagnosticInfos: [],
                  icons: [],
                  good: false,
                },
                {
                  name: 'Une rime suffisante',
                  value: 1,
                  _id: '55a78723b400730300932cce',
                  diagnosticInfos: [],
                  icons: [],
                  good: false,
                },
                {
                  name: 'Une rime pauvre',
                  value: 2,
                  _id: '55a78723b400730300932ccd',
                  diagnosticInfos: [],
                  icons: [],
                  good: false,
                },
                {
                  name: 'Une rime suffisante et une assonance',
                  value: 3,
                  _id: '55a78723b400730300932ccc',
                  diagnosticInfos: [],
                  icons: [],
                  good: true,
                },
              ],
              gapFill: {
                gaps: [],
              },
              swipeCards: {
                cards: [],
                choices: [],
              },
              slots: [],
              audios: [],
              icons: [],
              contentType: 'text',
              type: 'simple',
            },
          ],
          random: false,
          keyName: 'exitQuizz',
        },
        iconsPreview: [],
        contentPages: [],
        icons: [
          {
            _id: '55a789b0b400730300932cef',
            url: 'https://www.filepicker.io/api/file/BJmhafu1THeH4bKk4zfZ',
            filename: 'record-680826_640.jpg',
            mimetype: 'image/jpeg',
            size: 12345,
            key:
              'beedeez/dev/lessons/site/4LSpt9oyR1Olfk00uuWX_record-680826_640.jpg',
            type: 'site',
          },
          {
            _id: '55a789b0b400730300932cee',
            url: 'https://www.filepicker.io/api/file/SWiAEuSQ5mBbxYVqzqkV',
            filename: 'record-680826_640.jpg',
            mimetype: 'image/jpeg',
            size: 12345,
            key:
              'beedeez/dev/lessons/mobile/ymEy7TRiuCbS78jWYxjQ_record-680826_640.jpg',
            type: 'mobile',
          },
          {
            _id: '55a789b0b400730300932ced',
            url: 'https://www.filepicker.io/api/file/WXKnPHMzRKeceYRhnQwg',
            filename: 'record-680826_640.jpg',
            mimetype: 'image/jpeg',
            size: 1122,
            key:
              'beedeez/dev/lessons/small/fIXconIkQae1bYPSa9aN_record-680826_640.jpg',
            type: 'small',
          },
          {
            _id: '55a789b0b400730300932cec',
            url: 'https://www.filepicker.io/api/file/q9tOVmntSYSRpGcU9NLk',
            filename: 'record-680826_640.jpg',
            mimetype: 'image/jpeg',
            size: 819,
            key:
              'beedeez/dev/lessons/tiny/Mal55RjR02VUtVGcxPLF_record-680826_640.jpg',
            type: 'tiny',
          },
          {
            _id: '55a789b0b400730300932ceb',
            url: 'https://www.filepicker.io/api/file/rlnntJaGSVamc7CaIp6q',
            filename: 'record-680826_640.jpg',
            mimetype: 'image/jpeg',
            size: 178353,
            key:
              'beedeez/dev/lessons/img/ndaQwT65RbKMWaLodefc_record-680826_640.jpg',
            container: 'followus-dev',
            type: 'original',
          },
        ],
        slideshow: [],
        audio: [],
        video: [],
        flashCards: [],
        type: 'standard',
      },
      {
        name: 'Les formats de poèmes',
        content:
          'Il existe plusieurs formats fixes de poèmes, classiquement utilisés et répondant à des règles complexes. Ces formats sont déterminés par le nombre de strophes du poème, le type de ces strophes (tercet, quatrain, etc.), et l’organisation entre les rimes (ABBA, AABB, etc).\n\nPARMI LES FORMATS CLASSIQUES on trouve par exemple le RONDEAU (poème à 3 strophes formées sur 2 rimes : 1 quintil, 1 tercet, 1 quintil), la BALLADE (poème à 3 dizains ou huitains reprenant les mêmes rimes et suivis d’une strophe plus courte appelée envoi), ou encore le TRIOLET (poème à 3 strophes de 8 octosyllabes).\n\nLE SONNET est le format de poème le plus connu. Il se compose de 2 quatrains dont les rimes sont habituellement embrassées (ABBA), et de 2 tercets fondés sur deux autres rimes.\nParmi les célèbres sonnets on peut citer « Mon rêve familier » de Paul Verlaine, « Le Dormeur du val » d’Arthur Rimbaud, ou encore « A une passante » de Charles Baudelaire.',
        _id: '55a78723b400730300932cba',
        entryQuizz: {
          isPositioningQuiz: true,
          diagnostic: {
            axes: [],
            themes: [],
          },
          lifeNumber: 1,
          questions: [
            {
              title: 'Un sonnet est un poème :',
              _id: '55a78723b400730300932cbb',
              points: 1,
              explanationIsCompulsory: false,
              survey: false,
              choices: [
                {
                  name: 'à 6 strophes',
                  value: 0,
                  _id: '55a78723b400730300932cbf',
                  diagnosticInfos: [],
                  icons: [],
                  good: false,
                },
                {
                  name: 'à 2 quatrains et 2 tercets',
                  value: 1,
                  _id: '55a78723b400730300932cbe',
                  diagnosticInfos: [],
                  icons: [],
                  good: true,
                },
                {
                  name: 'qui repose sur le son « s »',
                  value: 2,
                  _id: '55a78723b400730300932cbd',
                  diagnosticInfos: [],
                  icons: [],
                  good: false,
                },
                {
                  name: 'de forme contemporaine',
                  value: 3,
                  _id: '55a78723b400730300932cbc',
                  diagnosticInfos: [],
                  icons: [],
                  good: false,
                },
              ],
              gapFill: {
                gaps: [],
              },
              swipeCards: {
                cards: [],
                choices: [],
              },
              slots: [],
              audios: [],
              icons: [],
              contentType: 'text',
              type: 'simple',
            },
          ],
          random: false,
          keyName: 'entryQuizz',
        },
        quizz: {
          diagnostic: {
            axes: [],
            themes: [],
          },
          lifeNumber: 1,
          questions: [
            {
              title:
                'Les 2 quatrains d’un sonnet ont classiquement des rimes :',
              _id: '55a78723b400730300932cc0',
              points: 1,
              explanationIsCompulsory: false,
              survey: false,
              choices: [
                {
                  name: 'Croisées',
                  value: 0,
                  _id: '55a78723b400730300932cc4',
                  diagnosticInfos: [],
                  icons: [],
                  good: false,
                },
                {
                  name: 'Embrassées',
                  value: 1,
                  _id: '55a78723b400730300932cc3',
                  diagnosticInfos: [],
                  icons: [],
                  good: true,
                },
                {
                  name: 'Plates',
                  value: 2,
                  _id: '55a78723b400730300932cc2',
                  diagnosticInfos: [],
                  icons: [],
                  good: false,
                },
                {
                  name: 'Intérieures',
                  value: 3,
                  _id: '55a78723b400730300932cc1',
                  diagnosticInfos: [],
                  icons: [],
                  good: false,
                },
              ],
              gapFill: {
                gaps: [],
              },
              swipeCards: {
                cards: [],
                choices: [],
              },
              slots: [],
              audios: [],
              icons: [],
              contentType: 'text',
              type: 'simple',
            },
          ],
          random: false,
          keyName: 'exitQuizz',
        },
        iconsPreview: [],
        contentPages: [],
        icons: [
          {
            _id: '55a789b0b400730300932cea',
            url: 'https://www.filepicker.io/api/file/7YwDU2nYTqm0StW5iMfo',
            filename: 'books-690219_640.jpg',
            mimetype: 'image/jpeg',
            size: 4375,
            key:
              'beedeez/dev/lessons/site/dAelQVWTMiRHRP02OtdF_books-690219_640.jpg',
            type: 'site',
          },
          {
            _id: '55a789b0b400730300932ce9',
            url: 'https://www.filepicker.io/api/file/UK9viyoLSCqkAC8QtAW0',
            filename: 'books-690219_640.jpg',
            mimetype: 'image/jpeg',
            size: 4375,
            key:
              'beedeez/dev/lessons/mobile/T3MEYS96QHmXDKGYHYz3_books-690219_640.jpg',
            type: 'mobile',
          },
          {
            _id: '55a789b0b400730300932ce8',
            url: 'https://www.filepicker.io/api/file/oaWtyI1JTnGcafKPweBN',
            filename: 'books-690219_640.jpg',
            mimetype: 'image/jpeg',
            size: 1033,
            key:
              'beedeez/dev/lessons/small/tbyrVpA5Q66VovtMXbqV_books-690219_640.jpg',
            type: 'small',
          },
          {
            _id: '55a789b0b400730300932ce7',
            url: 'https://www.filepicker.io/api/file/cp2e6LDRlGTGtTM6XVOg',
            filename: 'books-690219_640.jpg',
            mimetype: 'image/jpeg',
            size: 610,
            key:
              'beedeez/dev/lessons/tiny/qntCxBZsSmqtGodNYNKN_books-690219_640.jpg',
            type: 'tiny',
          },
          {
            _id: '55a789b0b400730300932ce6',
            url: 'https://www.filepicker.io/api/file/QyHm8ZdaSRCsEDAzhkXw',
            filename: 'books-690219_640.jpg',
            mimetype: 'image/jpeg',
            size: 35139,
            key:
              'beedeez/dev/lessons/img/V7ZgdO3WQJqkMGaOCmi8_books-690219_640.jpg',
            container: 'followus-dev',
            type: 'original',
          },
        ],
        slideshow: [],
        audio: [],
        video: [],
        flashCards: [],
        type: 'standard',
      },
    ],
    tags: '',
    metrics: {
      ratings: 0,
      view: 0,
      share: 0,
      like: 0,
      score: 0,
    },
    icons: [],
    _accessingUserGroupIds: [],
    _accessingTrackIds: [],
    _trackOrganization: [],
    sources: [],
    images: [
      {
        _id: '55a789b0b400730300932cf9',
        url: 'https://www.filepicker.io/api/file/WPZxhawSS7OPMoTikBRT',
        filename: 'abc-390026_640.jpg',
        mimetype: 'image/jpeg',
        size: 9463,
        key: 'beedeez/dev/lessons/site/rgqsG8FuT0qa3hCBPCO0_abc-390026_640.jpg',
        type: 'site',
      },
      {
        _id: '55a789b0b400730300932cf8',
        url: 'https://www.filepicker.io/api/file/UkqOezFRAuN6iMbzWScg',
        filename: 'abc-390026_640.jpg',
        mimetype: 'image/jpeg',
        size: 9463,
        key:
          'beedeez/dev/lessons/mobile/VM3jr6PDQp6yNbjlcc2K_abc-390026_640.jpg',
        type: 'mobile',
      },
      {
        _id: '55a789b0b400730300932cf7',
        url: 'https://www.filepicker.io/api/file/13OZ4j7rQEmajDyb6c0C',
        filename: 'abc-390026_640.jpg',
        mimetype: 'image/jpeg',
        size: 1141,
        key:
          'beedeez/dev/lessons/small/eMPZ40pSzDT8nD87mMxw_abc-390026_640.jpg',
        type: 'small',
      },
      {
        _id: '55a789b0b400730300932cf6',
        url: 'https://www.filepicker.io/api/file/Yciu0V7xQYSpSXqfa8Lb',
        filename: 'abc-390026_640.jpg',
        mimetype: 'image/jpeg',
        size: 648,
        key: 'beedeez/dev/lessons/tiny/YkWffRv2ArDFvcKaeQnG_abc-390026_640.jpg',
        type: 'tiny',
      },
      {
        _id: '55a789b0b400730300932cf5',
        url: 'https://www.filepicker.io/api/file/k5UDTqtWRrCjcTQ6Rq0c',
        filename: 'abc-390026_640.jpg',
        mimetype: 'image/jpeg',
        size: 70340,
        key: 'beedeez/dev/lessons/img/GvfvugAzRoWwShMYqrsu_abc-390026_640.jpg',
        container: 'followus-dev',
        type: 'original',
      },
    ],
    links: [],
    _id: '5cd933aa659dfc0050008739',
  },
];
